// @SnAPI.Title("Example API")
// @SnAPI.Description("This is an example API generated by SnAPI.")
// @SnAPI.Version("1.0.0")
// @SnAPI.Server("http://localhost:8080", "local development")
// @SnAPI.Server("https://api.example.local", "production")
// @SnAPI.SecurityScheme("bearerAuth", "http", "bearer", "JWT")
// @SnAPI.StaticFile("/static", "./public")
package api
