// @SnAPI.Title("Example API")
// @SnAPI.Description("This is an example API generated by SnAPI.")
// @SnAPI.Version("1.0.0")
// @SnAPI.Server("http://localhost:8080", "local development")
// @SnAPI.Server("https://api.example.local", "production")
// @SnAPI.SecurityScheme("bearerAuth", "http", "bearer", "JWT")
package api

import (
	"encoding/xml"
	"fmt"
	"net/http"
	"strings"

	"github.com/StevenCyb/SnAPI/pkg/runtime"
	"github.com/StevenCyb/example/pkg/model"
	"github.com/google/uuid"
)

// @SnAPI.GET()
// @SnAPI.Deprecated
// @SnAPI.Status(200)
// @SnAPI.Description("This is the root endpoint.")
// @SnAPI.Tags("example", "root")
// @SnAPI.UseMiddleware(api.LoggingMiddleware)
func GetRoot(r runtime.Request, w runtime.Response) {
	w.Html(http.StatusOK, fmt.Sprintf("<h1>Hello, %s!</h1>", config.Name))
}

// @SnAPI.GET("/todo/{id}")
// @SnAPI.Tags("todo")
// @SnAPI.Summary("Get a single todo by id")
// @SnAPI.OperationID("getTodoById")
// @SnAPI.Path("id", "string", "todo identifier")
// @SnAPI.Header("X-Request-Id", "string", "client trace id", "false")
// @SnAPI.Status(200, "OK")
// @SnAPI.Response(200, "application/json", model.Todo)
// @SnAPI.Status(404, "todo not found")
// @SnAPI.UseMiddleware(api.LoggingMiddleware)
func GetTodo(r runtime.Request, w runtime.Response) {
	id := r.PathValue("id")
	todo, ok := todoRepo.Get(id)
	if !ok {
		w.Error(http.StatusNotFound, "todo not found")
		return
	}
	w.Json(http.StatusOK, todo)
}

// @SnAPI.GET("/todos")
// @SnAPI.Tags("todo")
// @SnAPI.OperationID("listTodos")
// @SnAPI.Query("q", "string", "filter todos by title substring", "false")
// @SnAPI.Status(200, "OK")
// @SnAPI.Response(200, "application/json", []model.Todo)
// @SnAPI.ResponseHeader(200, "X-Total-Count", "integer", "total number of items")
// @SnAPI.UseMiddleware(api.LoggingMiddleware)
func ListTodos(r runtime.Request, w runtime.Response) {
	query := r.QueryValue("q")
	todos := todoRepo.List()

	if query == "" {
		w.Json(http.StatusOK, todos)
		return
	}

	filtered := make([]model.Todo, 0)
	for _, todo := range todos {
		if strings.Contains(todo.Title, query) {
			filtered = append(filtered, todo)
		}
	}
	w.Json(http.StatusOK, filtered)
}

// @SnAPI.POST("/todo")
// @SnAPI.Tags("todo")
// @SnAPI.Request("application/json", model.Todo)
// @SnAPI.Request("application/xml", model.Todo)
// @SnAPI.Status(200, "OK")
// @SnAPI.Status(400, "invalid request body")
// @SnAPI.UseMiddleware(api.LoggingMiddleware)
func CreateTodo(r runtime.Request, w runtime.Response) {
	var todo model.Todo
	switch r.Header("Content-Type") {
	case "application/json":
		if err := r.FromJsonBody(&todo); err != nil {
			w.Error(http.StatusBadRequest, "invalid request body")
			return
		}
	case "application/xml":
		if err := xml.NewDecoder(r.Raw().Body).Decode(&todo); err != nil {
			w.Error(http.StatusBadRequest, "invalid request body")
			return
		}
	default:
		w.Error(http.StatusUnsupportedMediaType, "unsupported content type")
		return
	}
	todo.ID = uuid.New().String()
	todoRepo.Update(todo)
	w.Json(http.StatusOK, todo)
}

// @SnAPI.DELETE("/todo/{id}")
// @SnAPI.Tags("todo")
// @SnAPI.Status(204, "No Content")
// @SnAPI.Status(404, "todo not found")
// @SnAPI.UseMiddleware(api.LoggingMiddleware)
func DeleteTodo(r runtime.Request, w runtime.Response) {
	id := r.PathValue("id")
	if !todoRepo.Delete(id) {
		w.Error(http.StatusNotFound, "todo not found")
		return
	}
	w.Status(http.StatusNoContent)
}

// @SnAPI.PUT("/todo/{id}")
// @SnAPI.Tags("todo")
// @SnAPI.Request("application/json", model.Todo)
// @SnAPI.Status(200, "OK")
// @SnAPI.Status(400, "invalid request body")
// @SnAPI.Status(404, "todo not found")
// @SnAPI.UseMiddleware(api.LoggingMiddleware)
func UpdateTodo(r runtime.Request, w runtime.Response) {
	id := r.PathValue("id")
	if _, ok := todoRepo.Get(id); !ok {
		w.Error(http.StatusNotFound, "todo not found")
		return
	}
	var todo model.Todo
	if err := r.FromJsonBody(&todo); err != nil {
		w.Error(http.StatusBadRequest, "invalid request body")
		return
	}
	todo.ID = id
	todoRepo.Update(todo)
	w.Json(http.StatusOK, todo)
}

// @SnAPI.GET("/me")
// @SnAPI.Tags("auth")
// @SnAPI.Summary("Get the authenticated user's profile")
// @SnAPI.OperationID("getMyProfile")
// @SnAPI.Security("bearerAuth")
// @SnAPI.Header("X-Request-Id", "string", "client trace id", "false")
// @SnAPI.Cookie("session", "string", "opaque session token", "false")
// @SnAPI.Status(200, "OK")
// @SnAPI.Response(200, "application/json", model.Profile)
// @SnAPI.ResponseHeader(200, "X-Rate-Limit-Remaining", "integer", "requests remaining in window")
// @SnAPI.Status(401, "missing or invalid bearer token")
// @SnAPI.UseMiddleware(api.LoggingMiddleware)
func GetProfile(r runtime.Request, w runtime.Response) {
	auth := r.Header("Authorization")
	if !strings.HasPrefix(auth, "Bearer ") {
		w.Error(http.StatusUnauthorized, "missing bearer token")
		return
	}
	w.Json(http.StatusOK, model.Profile{
		ID:    "u-1",
		Name:  "Ada Lovelace",
		Email: "ada@example.com",
	})
}
