// Code generated by snapi. DO NOT EDIT.
package main

import (
	"context"
	"log"
	"net/http"
	"os/signal"
	"syscall"
	"time"

	"github.com/StevenCyb/SnAPI/pkg/runtime"
)

const addr = ":8080"

func main() {
	rootMux := http.NewServeMux()

	handlerFuncMux := http.NewServeMux()
	registerRoutes(handlerFuncMux)
	rootMux.Handle("/", handlerFuncMux)

	srv := &http.Server{
		Addr:    addr,
		Handler: rootMux,
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen: %s\n", err)
		}
	}()
	log.Printf("Server started on %s\n", addr)

	<-ctx.Done()
	log.Println("Shutting down server...")

	ctxShutDown, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctxShutDown); err != nil {
		log.Fatalf("Server Shutdown Failed: %v\n", err)
	}

	log.Println("Server exited properly.")
}

func registerRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/hello/{name}", func(w http.ResponseWriter, r *http.Request) {
		name := r.PathValue("name")
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		_, _ = w.Write([]byte("Hello, " + name + "!"))
	})

	mux.HandleFunc("/hello2/{name}", runtime.WrapHandlerFunc(func(req runtime.Request, resp runtime.Response) {
		Greeter(req, resp)
	}))
	// mux.HandleFunc("/items", ListItems)
	// mux.HandleFunc("/items/{id}", GetItem)
	// mux.HandleFunc("/items", CreateItem)
	// mux.HandleFunc("/items/{id}", UpdateItem)
	// mux.HandleFunc("/items/{id}", DeleteItem)
}

func Greeter(req runtime.Request, resp runtime.Response) {
	name := req.PathValue("name")
	resp.Text(http.StatusOK, "Hello, "+name+"!")
}
