// @SnAPI.Title("Example Proto API")
// @SnAPI.Description("Handlers + DTOs generated by `snapi proto` from todo.proto.")
// @SnAPI.Version("1.0.0")
// @SnAPI.Server("http://localhost:8080", "local development")
package api
